### ISSUE TITLE
Limit Song preview time

### ISSUE THREAD

**Issue by stickyfran** [dj505/Infinitesimal#20]
Is there a way to limit the time that a song shows you how it sounds when you are scrolling?
I mean, it plays the full song and it would be great to only listen 10s or something, stop and then play the "menu music".

**Comment by dj505** [comment]
If you have notefield previews enabled it'll play the entire song starting from when the preview would normally start to prevent the preview from freezing in place. You'll need to disable the preview in the "Infinitesimal Settings" submenu of the operator menu if you want to revert to shorter previews
