### ISSUE TITLE
profile name is covered by credits text when playing a doubles chart

### ISSUE THREAD

**Issue by piotr25691** [dj505/Infinitesimal#21]
The profile name is covered by the credits text when you play a double chart.

![image](https://user-images.githubusercontent.com/71488561/177033940-0b0da963-2d69-457f-a7b2-2e74cd9d01de.png)

**Comment by SheepyChris** [comment]
Fixed in the latest commit, the profile name will only center now if the credits text isn't visible (aka in home mode). The positioning code was made before the credits text was reintroduced, so it was an oversight on my part.
