### ISSUE TITLE
Is this supposed to happen?

### ISSUE THREAD

**Issue by piotr25691** [dj505/Infinitesimal#30]
I failed a couple songs on a new profile and my level dropped from Level 1 to "Level -nan(ind)".
What's up with that?

![image](https://user-images.githubusercontent.com/71488561/201478678-98800c12-1e35-469f-ac05-24b2b3847fbc.png)

**Comment by dj505** [comment]
Probably an easy fix, I'll take a look when I get home from work if sheepychris doesn't best me to it

**Comment by piotr25691** [comment]
> Probably an easy fix, I'll take a look when I get home from work if sheepychris doesn't beat me to it

Also it looks like I can now fail songs even when I have Event Mode and Fail Off set

**Comment by SheepyChris** [comment]
I don't recall touching anything related to failing stages, are you able to
test if the issue persists on the default OutFox theme?

**Comment by piotr25691** [comment]
> Yes, it fails out on the default theme as well.

Here's what Fail is set to:
![image](https://user-images.githubusercontent.com/71488561/201486226-d6dc3254-1e9a-4839-b9d1-01d7ec0b2428.png)
