### ISSUE TITLE
Lite bugs

### ISSUE THREAD

**Issue by mattyx14** [dj505/Infinitesimal#53]
I have seen that there are some minor errors
1. Previously when you were in a song in basic mode, automatically changing to full mode does not leave you in the song that you were previously in basic mode, which in previous versions it did, placing you in the special menu and not in albums
2. Also when the counter reaches 0 it does not advance automatically to automatic selection

I have only observed these details in Pay mode but I suppose it applies to all modes

Outfox V lasted 
OutFox-0.5.0-pre043-a17-Win64-date-20240820

**Comment by celunah** [comment]
Since you're not supposed to operate this in Pay Mode I assume, it's gonna be a wontfix

**Comment by dj505** [comment]
Pay mode is allowed since post-rewrite when we removed any references to Andamiro intellectual property, I just haven't had time to work on this lately 😞

**Comment by SheepyChris** [comment]
Timer not functioning has been fixed with commit `f2fdba0`, the song wheel position being reset while transitioning from Basic to Full mode is intentional behavior
