### ISSUE TITLE
Infinitesimal Menu

### ISSUE THREAD

**Issue by amarant24** [dj505/Infinitesimal#7]
I love the theme and it works amazing.
The menu doesn't have a "Select Game" option which would make the difference between the theme being perfect and not.

**Comment by SheepyChris** [comment]
Would the "Select Game" option you mention be related to the StepMania gamemodes (dance, pump, etc) or the Arcade/Pro modes? If the latter, they are currently accessible if no player profile is present. They are soon going to be reworked whenever I have the time again, and if this is the case I will add an option to disable that functionality.

**Comment by SheepyChris** [comment]
Added option and fixed play modes with commit 60c251358a0fdb47cd9bb3ad1814252ba5e032e9.
